[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy: "default-src 'https:'"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=15768000"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"
